
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'queryCOMMA COUNT DE DONDE EL LAS LO LOS O SEA SHOW STRING Yignore : ELignore : LOSignore : LASignore : LOignore_opt : ignore\n                  | emptyempty :field_list : STRINGfield_list : field_list COMMA STRING\n                  | field_list Y STRING\n                  | field_list COMMA Y STRING\n                  | field_list O STRINGcondition : DONDE condition_listcondition_opt : condition\n                     | emptycondition_list : STRING SEA STRINGquery : SHOW ignore_opt field_list DE STRING condition_opt'
    
_lr_action_items = {'SHOW':([0,],[2,]),'$end':([1,16,21,22,23,26,29,],[0,-7,-17,-14,-15,-13,-16,]),'EL':([2,],[6,]),'LOS':([2,],[7,]),'LAS':([2,],[8,]),'LO':([2,],[9,]),'STRING':([2,3,4,5,6,7,8,9,12,13,14,15,18,24,28,],[-7,11,-5,-6,-1,-2,-3,-4,16,17,19,20,25,27,29,]),'DE':([10,11,17,19,20,25,],[12,-8,-9,-10,-12,-11,]),'COMMA':([10,11,17,19,20,25,],[13,-8,-9,-10,-12,-11,]),'Y':([10,11,13,17,19,20,25,],[14,-8,18,-9,-10,-12,-11,]),'O':([10,11,17,19,20,25,],[15,-8,-9,-10,-12,-11,]),'DONDE':([16,],[24,]),'SEA':([27,],[28,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'query':([0,],[1,]),'ignore_opt':([2,],[3,]),'ignore':([2,],[4,]),'empty':([2,16,],[5,23,]),'field_list':([3,],[10,]),'condition_opt':([16,],[21,]),'condition':([16,],[22,]),'condition_list':([24,],[26,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> query","S'",1,None,None,None),
  ('ignore -> EL','ignore',1,'p_ignore_article_el','parser.py',33),
  ('ignore -> LOS','ignore',1,'p_ignore_article_los','parser.py',34),
  ('ignore -> LAS','ignore',1,'p_ignore_article_las','parser.py',35),
  ('ignore -> LO','ignore',1,'p_ignore_article_lo','parser.py',36),
  ('ignore_opt -> ignore','ignore_opt',1,'p_ignore_opt','parser.py',38),
  ('ignore_opt -> empty','ignore_opt',1,'p_ignore_opt','parser.py',39),
  ('empty -> <empty>','empty',0,'p_empty','parser.py',43),
  ('field_list -> STRING','field_list',1,'p_field_list_single','parser.py',45),
  ('field_list -> field_list COMMA STRING','field_list',3,'p_field_list_multi','parser.py',49),
  ('field_list -> field_list Y STRING','field_list',3,'p_field_list_multi','parser.py',50),
  ('field_list -> field_list COMMA Y STRING','field_list',4,'p_field_list_multi','parser.py',51),
  ('field_list -> field_list O STRING','field_list',3,'p_field_list_multi','parser.py',52),
  ('condition -> DONDE condition_list','condition',2,'p_condition','parser.py',56),
  ('condition_opt -> condition','condition_opt',1,'p_condition_opt','parser.py',60),
  ('condition_opt -> empty','condition_opt',1,'p_condition_opt','parser.py',61),
  ('condition_list -> STRING SEA STRING','condition_list',3,'p_condition_list_simple','parser.py',68),
  ('query -> SHOW ignore_opt field_list DE STRING condition_opt','query',6,'p_query_mostrar_varios','parser.py',76),
]
